<?php
	define("HRVT_ERROR_NO_PERMISSION", 0);
	define("HRVT_ERROR_COLLECTION_NOT_EXIST", 1);
	define("HRVT_ERROR_FACTOID_NOT_EXIST", 2);
	define("HRVT_ERROR_INVALID_CALENDAR", 3);
	
	define("HRVT_FACTOID_SORT_ID", 0);
	define("HRVT_FACTOID_SORT_CTIME", 1);
	define("HRVT_FACTOID_SORT_UTIME", 2);
	define("HRVT_FACTOID_SORT_TITLE", 3);
	define("HRVT_FACTOID_SORT_VALUE", 4);
	define("HRVT_FACTOID_SORT_COMMENTS", 5);
	define("HRVT_FACTOID_SORT_SDATE", 6);
	define("HRVT_FACTOID_SORT_EDATE", 7);
?>